# Generated by Django 3.1.6 on 2021-03-01 09:00

import ZakharovMachineLearn.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZakharovMachineLearn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='blog/images/already.png', upload_to=ZakharovMachineLearn.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ZakharovMachineLearn.postcategory'),
        ),
    ]
