# Generated by Django 3.1.6 on 2021-02-21 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZakharovMachineLearn', '0004_post_estimation_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimation_set', to='ZakharovMachineLearn.post'),
        ),
    ]
