# Generated by Django 3.1.6 on 2021-02-22 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZakharovMachineLearn', '0005_auto_20210221_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
