# Generated by Django 3.1.6 on 2021-02-28 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZakharovMachineLearn', '0007_auto_20210222_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_markdown',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(help_text='Тело поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comment_amount',
            field=models.IntegerField(default=0, help_text='Количество комментариев'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='estimation_amount',
            field=models.IntegerField(default=0, help_text='Количество оценок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Включен ли в выдачу'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.FloatField(default=0, help_text='Рейтинг поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Заголовок поста', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Дата обновления контента'),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0, help_text='Количество просмотров'),
        ),
    ]
